name: Docker Latest Push

on:
  push:

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
  
      - name: Build the static content
        run: |
          yarn install
          yarn run build
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: skymind-website
          path: build/
  
  deploy:
      needs: build
      name: Push to Docker Hub
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: skymind-website
          path: build/

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/skyweb:nightly
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/skyweb:nightly
